### ISSUE TITLE
Traceback (most recent call last): File "requests\models.py", line 971, in json File "json\_init_.py•, line 346, in loads File "json\decoder.py•, line 337, in decode File "json\decoder.py•, line 355, in raw_decode json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "壁纸生成器V4.py"，line 4564, in GetAlGenerated r = response.json() File "requests\models.py", line 975, in json requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char O)

### ISSUE THREAD

**Issue by ItsTimeTooSleep** [SRInternet-Studio/Wallpaper-generator#4]
![局部截取_20241216_195320](https://github.com/user-attachments/assets/e34cf069-1d28-4d4b-a153-aa8d0937f4bc)

**Comment by jiangyin14** [comment]
技术人员正在修复这个问题，请稍等。
有新的维护进展会在此处向您回复，感谢您的支持。

**Comment by jiangyin14** [comment]
已修复。
